services:
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix
    platform: linux/amd64
    ports:
      - "6006:6006"
      - "4317:4317"
    env_file:
      - .env
    volumes:
      - phoenix_data:/var/lib/phoenix
    networks:
      - app_network

volumes:
  phoenix_data:

networks:
  app_network:
    driver: bridge
